### ISSUE TITLE
GKE/EKS: mkdir: cannot create directory ‘/data/pgdata’: Permission denied

### ISSUE THREAD

**Issue by kumo-rn5s** [dev4devs-com/postgresql-operator#94]
## Question
I got this error in my GKE & EKS deployments by running `make install`, but it works well on my local minikube.
Through searching, I think this may be related to the securityContext setting.

Like this
```yaml
 securityContext:
    runAsUser: 1000
    fsGroup: 2000
```

So this is what you mean about `To install you need be logged in as a user with cluster privileges like the system:admin user.` in README? 

How can i add securityContext setting to Pod?
